version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always